site_name: Автоматизированная система управления заказами в роботизированном ресторане
nav:
  - Home: index.md
  - Общее описание: about.md
  - Требования к системе: index.md
  - Информационная модель: onemore.md
  - Компонентная архитектура: onemore.md
  - API: onemore.md
  - Пользовательский интерфейс: onemore.md
  - Задачи: onemore.md
  - Тест-кейсы: onemore.md

